# Dependencies
gems: [jekyll-paginate]
gems: [jekyll-gist]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Naveen Kumar M
tagline:          'Software Developer'
description:      'Page about myself <a href="www.facebook.com/naveenkhasyap" target="_blank">n@vy</a>'
url:              http://github.com/Naveenkhasyap
baseurl:          /

author:
  name:           'Naveen Kumar M'
  url:            https://twitter.com/naveen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Naveenkhasyap
